scan_filter_chain:
- name: rangoChido
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 1.5
    upper_threshold: .inf
    lower_replacement_value: -.inf
    upper_replacement_value: .inf