# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaYaEsHora.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaYaEsHora(object):
    def setupUi(self, ventanaYaEsHora):
        ventanaYaEsHora.setObjectName("ventanaYaEsHora")
        ventanaYaEsHora.resize(326, 243)
        self.label = QtWidgets.QLabel(ventanaYaEsHora)
        self.label.setGeometry(QtCore.QRect(50, 80, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_nombreYaEsHora = QtWidgets.QLabel(ventanaYaEsHora)
        self.label_nombreYaEsHora.setGeometry(QtCore.QRect(30, 140, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.label_nombreYaEsHora.setFont(font)
        self.label_nombreYaEsHora.setText("")
        self.label_nombreYaEsHora.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nombreYaEsHora.setObjectName("label_nombreYaEsHora")
        self.pushButton_2 = QtWidgets.QPushButton(ventanaYaEsHora)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 200, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(ventanaYaEsHora)
        self.label_2.setGeometry(QtCore.QRect(60, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_hr_YaEsHora = QtWidgets.QLabel(ventanaYaEsHora)
        self.label_hr_YaEsHora.setGeometry(QtCore.QRect(170, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        self.label_hr_YaEsHora.setFont(font)
        self.label_hr_YaEsHora.setText("")
        self.label_hr_YaEsHora.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hr_YaEsHora.setObjectName("label_hr_YaEsHora")

        self.retranslateUi(ventanaYaEsHora)
        QtCore.QMetaObject.connectSlotsByName(ventanaYaEsHora)

    def retranslateUi(self, ventanaYaEsHora):
        _translate = QtCore.QCoreApplication.translate
        ventanaYaEsHora.setWindowTitle(_translate("ventanaYaEsHora", "Es hora de un medicamento"))
        self.label.setText(_translate("ventanaYaEsHora", "Es hora de la medicina de:"))
        self.pushButton_2.setText(_translate("ventanaYaEsHora", "Aceptar"))
        self.label_2.setText(_translate("ventanaYaEsHora", "Son las: "))
